2015-01-21 21:03:52,176 ERROR Error:
Error:
2015-01-21 21:05:36,940 ERROR Error:
2015-01-21 21:05:40,410 ERROR Error:
2015-01-21 21:08:03,985 ERROR Error:
2015-01-21 21:08:09,532 ERROR Error:
2015-01-21 21:15:42,863 ERROR Error:
2015-01-21 21:16:10,612 ERROR Error:
2015-01-21 21:16:10,612 ERROR Foo:
2015-01-21 21:17:50,001 /Users/renee/Projects/personal-projects/Pwitter/service/resources/protected_resource.py Error: 'NoneType' object has no attribute 'hashed_token'
2015-01-21 21:22:00,781 protected_resource.py Error: No user for 
2015-01-21 21:22:52,233 protected_resource.py Error: No user for foo
2015-01-21 22:54:38,721 protected_resource.py Error: No user for foo
2015-01-21 22:55:51,683 protected_resource.py Error: No user for US00000000000000
2015-01-21 22:57:29,090 protected_resource.py Error: No user for US00000000000000
2015-01-21 22:57:36,376 protected_resource.py Error: No user for US00000000000000
2015-01-21 22:57:47,688 protected_resource.py Error: No user for US00000000000000
2015-01-21 22:58:20,264 protected_resource.py Error: No user for US00000000000000
2015-01-21 22:58:54,827 protected_resource.py Error: No user for US00000000000000
2015-01-21 22:59:11,220 protected_resource.py Error: No user for US00000000000000
2015-01-21 23:00:36,059 protected_resource.py Error: No user for US00000000000000
2015-01-21 23:01:04,870 protected_resource.py Error: No user for US00000000000000
2015-01-21 23:01:28,825 protected_resource.py Error: No user for US00000000000000
2015-01-21 23:06:40,637 protected_resource.py Error: No user for US00000000000000
2015-01-21 23:06:51,843 protected_resource.py Error: No user for US00000000000000
2015-01-21 23:07:00,757 protected_resource.py Error: No user for US00000000000000
2015-01-21 23:08:03,254 protected_resource.py Error: No user for US00000000000000
2015-01-21 23:08:12,147 protected_resource.py Error: No user for US00000000000000
2015-01-21 23:08:19,422 protected_resource.py Error: No user for US00000000000000
2015-01-21 23:46:54,946 protected_resource.py FOOOO
2015-01-21 23:46:54,946 protected_resource.py Error: No user for foo
2015-01-21 23:47:27,436 protected_resource.py FOOOO
2015-01-21 23:47:27,436 protected_resource.py Error: No user for foo
2015-01-21 23:47:32,872 protected_resource.py FOOOO
2015-01-21 23:47:32,872 protected_resource.py Error: No user for foo
2015-01-21 23:52:48,658 protected_resource.py FOOOO
2015-01-21 23:52:48,658 protected_resource.py Error: No user for foo
2015-01-21 23:53:11,014 protected_resource.py FOOOO
2015-01-21 23:53:11,014 protected_resource.py Error: No user for foo
2015-01-21 23:53:11,024 protected_resource.py FOOOO
2015-01-21 23:53:11,024 protected_resource.py Error: No user for US00000000000001
2015-01-21 23:53:57,748 protected_resource.py FOOOO
2015-01-21 23:53:57,748 protected_resource.py Error: No user for foo
2015-01-21 23:54:17,843 protected_resource.py FOOOO
2015-01-21 23:54:17,843 protected_resource.py Error: No user for foo
2015-01-21 23:54:17,858 protected_resource.py FOOOO
2015-01-21 23:54:17,858 protected_resource.py Error: No user for US00000000000001
2015-01-21 23:57:16,273 protected_resource.py FOOOO
2015-01-21 23:57:16,273 protected_resource.py Error: No user for foo
2015-01-21 23:57:55,767 protected_resource.py FOOOO
2015-01-21 23:57:55,767 protected_resource.py Error: No user for foo
2015-01-21 23:59:19,542 protected_resource.py FOOOO
2015-01-21 23:59:19,542 protected_resource.py Error: No user for foo
2015-01-21 23:59:44,727 protected_resource.py FOOOO
2015-01-21 23:59:44,727 protected_resource.py Error: No user for foo
2015-01-22 00:00:58,634 protected_resource.py FOOOO
2015-01-22 00:00:58,634 protected_resource.py Error: No user for foo
2015-01-22 00:01:19,788 protected_resource.py FOOOO
2015-01-22 00:01:19,788 protected_resource.py Error: No user for foo
2015-01-22 00:03:38,743 protected_resource.py FOOOO
2015-01-22 00:03:38,743 protected_resource.py Error: No user for foo
2015-01-22 00:03:49,578 protected_resource.py FOOOO
2015-01-22 00:03:49,578 protected_resource.py Error: No user for foo
2015-01-22 00:07:11,283 protected_resource.py FOOOO
2015-01-22 00:07:11,284 protected_resource.py Error: No user for foo
2015-01-22 00:08:52,246 protected_resource.py FOOOO
2015-01-22 00:08:52,246 protected_resource.py Error: No user for foo
2015-01-22 00:09:01,870 protected_resource.py FOOOO
2015-01-22 00:09:01,870 protected_resource.py Error: No user for foo
2015-02-01 13:14:24,269 protected_resource.py FOOOO
2015-02-01 13:14:24,270 protected_resource.py Error: No user for -u
2015-02-01 13:15:38,810 protected_resource.py FOOOO
2015-02-01 13:15:38,810 protected_resource.py Error: No user for US9888d60335c34f
2015-02-01 13:42:33,402 protected_resource.py There was an error
2015-02-01 13:42:33,402 protected_resource.py {'connection_invalidated': False, 'params': ('2015-02-01 13:42:33.401516', '2015-02-01 13:42:33.401523', 1, u'reneighbor', u'dogs are the best'), 'statement': u'INSERT INTO tweet (date_created, date_updated, user_id, username, body) VALUES (?, ?, ?, ?, ?)', 'orig': IntegrityError('column username is not unique',)}
2015-02-01 13:43:16,090 protected_resource.py There was an error
2015-02-01 13:43:16,091 protected_resource.py {'connection_invalidated': False, 'params': ('2015-02-01 13:43:16.089324', '2015-02-01 13:43:16.089331', 1, u'reneighbor', u'dogs are the best'), 'statement': u'INSERT INTO tweet (date_created, date_updated, user_id, username, body) VALUES (?, ?, ?, ?, ?)', 'orig': IntegrityError('column username is not unique',)}
2015-02-01 13:44:30,245 protected_resource.py There was an error
2015-02-01 13:44:30,245 protected_resource.py {'connection_invalidated': False, 'params': ('2015-02-01 13:44:30.244288', '2015-02-01 13:44:30.244295', 1, u'reneighbor', u'dogs are the best'), 'statement': u'INSERT INTO tweet (date_created, date_updated, user_id, username, body) VALUES (?, ?, ?, ?, ?)', 'orig': IntegrityError('column username is not unique',)}
2015-02-01 13:44:48,725 protected_resource.py There was an error
2015-02-01 13:44:48,725 protected_resource.py {'connection_invalidated': False, 'params': ('2015-02-01 13:44:48.724209', '2015-02-01 13:44:48.724215', 1, u'reneighbor', u'dogs are the best'), 'statement': u'INSERT INTO tweet (date_created, date_updated, user_id, username, body) VALUES (?, ?, ?, ?, ?)', 'orig': IntegrityError('column username is not unique',)}
2015-02-01 13:45:46,345 protected_resource.py There was an error
2015-02-01 13:45:46,345 protected_resource.py {'connection_invalidated': False, 'params': ('2015-02-01 13:45:46.344130', '2015-02-01 13:45:46.344137', 1, u'reneighbor', u'dogs are the best'), 'statement': u'INSERT INTO tweet (date_created, date_updated, user_id, username, body) VALUES (?, ?, ?, ?, ?)', 'orig': IntegrityError('column username is not unique',)}
2015-02-01 13:58:15,658 protected_resource.py There was an error
2015-02-01 13:58:15,659 protected_resource.py {'connection_invalidated': False, 'params': ('2015-02-01 13:58:15.657521', '2015-02-01 13:58:15.657528', 1, u'reneighbor', u'dogs are the best'), 'statement': u'INSERT INTO tweet (date_created, date_updated, user_id, username, body) VALUES (?, ?, ?, ?, ?)', 'orig': IntegrityError('column username is not unique',)}
2015-02-01 16:04:32,143 protected_resource.py There was an error
2015-02-01 16:04:32,143 protected_resource.py {}
2015-02-01 20:55:55,233 base_resource.py FOOOO
2015-02-01 20:55:55,233 base_resource.py Error: No user for foo
2015-02-01 20:56:01,769 base_resource.py FOOOO
2015-02-01 20:56:01,769 base_resource.py Error: No user for foo
